// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package dk.via.mithus.protobuf;

/**
 * Protobuf type {@code dk.via.mithus.protobuf.PostCreation}
 */
public final class PostCreation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dk.via.mithus.protobuf.PostCreation)
    PostCreationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PostCreation.newBuilder() to construct.
  private PostCreation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PostCreation() {
    title_ = "";
    description_ = "";
    creationDate_ = "";
    image_ = java.util.Collections.emptyList();
    amenity_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PostCreation();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PostCreation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 33: {

            area_ = input.readDouble();
            break;
          }
          case 40: {

            maxTenants_ = input.readInt32();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            creationDate_ = s;
            break;
          }
          case 56: {

            housingTypeId_ = input.readInt64();
            break;
          }
          case 64: {

            energyRatingId_ = input.readInt64();
            break;
          }
          case 72: {

            statusId_ = input.readInt64();
            break;
          }
          case 80: {

            landlordId_ = input.readInt64();
            break;
          }
          case 90: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              image_ = new java.util.ArrayList<dk.via.mithus.protobuf.Image>();
              mutable_bitField0_ |= 0x00000001;
            }
            image_.add(
                input.readMessage(dk.via.mithus.protobuf.Image.parser(), extensionRegistry));
            break;
          }
          case 98: {
            dk.via.mithus.protobuf.Address.Builder subBuilder = null;
            if (address_ != null) {
              subBuilder = address_.toBuilder();
            }
            address_ = input.readMessage(dk.via.mithus.protobuf.Address.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(address_);
              address_ = subBuilder.buildPartial();
            }

            break;
          }
          case 106: {
            dk.via.mithus.protobuf.Cost.Builder subBuilder = null;
            if (cost_ != null) {
              subBuilder = cost_.toBuilder();
            }
            cost_ = input.readMessage(dk.via.mithus.protobuf.Cost.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cost_);
              cost_ = subBuilder.buildPartial();
            }

            break;
          }
          case 114: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              amenity_ = new java.util.ArrayList<dk.via.mithus.protobuf.Amenity>();
              mutable_bitField0_ |= 0x00000002;
            }
            amenity_.add(
                input.readMessage(dk.via.mithus.protobuf.Amenity.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        image_ = java.util.Collections.unmodifiableList(image_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        amenity_ = java.util.Collections.unmodifiableList(amenity_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_PostCreation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_PostCreation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dk.via.mithus.protobuf.PostCreation.class, dk.via.mithus.protobuf.PostCreation.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private volatile java.lang.Object title_;
  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AREA_FIELD_NUMBER = 4;
  private double area_;
  /**
   * <code>double area = 4;</code>
   * @return The area.
   */
  @java.lang.Override
  public double getArea() {
    return area_;
  }

  public static final int MAXTENANTS_FIELD_NUMBER = 5;
  private int maxTenants_;
  /**
   * <code>int32 maxTenants = 5;</code>
   * @return The maxTenants.
   */
  @java.lang.Override
  public int getMaxTenants() {
    return maxTenants_;
  }

  public static final int CREATIONDATE_FIELD_NUMBER = 6;
  private volatile java.lang.Object creationDate_;
  /**
   * <code>string creationDate = 6;</code>
   * @return The creationDate.
   */
  @java.lang.Override
  public java.lang.String getCreationDate() {
    java.lang.Object ref = creationDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      creationDate_ = s;
      return s;
    }
  }
  /**
   * <code>string creationDate = 6;</code>
   * @return The bytes for creationDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCreationDateBytes() {
    java.lang.Object ref = creationDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      creationDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOUSINGTYPEID_FIELD_NUMBER = 7;
  private long housingTypeId_;
  /**
   * <code>int64 housingTypeId = 7;</code>
   * @return The housingTypeId.
   */
  @java.lang.Override
  public long getHousingTypeId() {
    return housingTypeId_;
  }

  public static final int ENERGYRATINGID_FIELD_NUMBER = 8;
  private long energyRatingId_;
  /**
   * <code>int64 energyRatingId = 8;</code>
   * @return The energyRatingId.
   */
  @java.lang.Override
  public long getEnergyRatingId() {
    return energyRatingId_;
  }

  public static final int STATUSID_FIELD_NUMBER = 9;
  private long statusId_;
  /**
   * <code>int64 statusId = 9;</code>
   * @return The statusId.
   */
  @java.lang.Override
  public long getStatusId() {
    return statusId_;
  }

  public static final int LANDLORDID_FIELD_NUMBER = 10;
  private long landlordId_;
  /**
   * <code>int64 landlordId = 10;</code>
   * @return The landlordId.
   */
  @java.lang.Override
  public long getLandlordId() {
    return landlordId_;
  }

  public static final int IMAGE_FIELD_NUMBER = 11;
  private java.util.List<dk.via.mithus.protobuf.Image> image_;
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
   */
  @java.lang.Override
  public java.util.List<dk.via.mithus.protobuf.Image> getImageList() {
    return image_;
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
   */
  @java.lang.Override
  public java.util.List<? extends dk.via.mithus.protobuf.ImageOrBuilder> 
      getImageOrBuilderList() {
    return image_;
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
   */
  @java.lang.Override
  public int getImageCount() {
    return image_.size();
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.Image getImage(int index) {
    return image_.get(index);
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.ImageOrBuilder getImageOrBuilder(
      int index) {
    return image_.get(index);
  }

  public static final int ADDRESS_FIELD_NUMBER = 12;
  private dk.via.mithus.protobuf.Address address_;
  /**
   * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return address_ != null;
  }
  /**
   * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
   * @return The address.
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.Address getAddress() {
    return address_ == null ? dk.via.mithus.protobuf.Address.getDefaultInstance() : address_;
  }
  /**
   * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.AddressOrBuilder getAddressOrBuilder() {
    return getAddress();
  }

  public static final int COST_FIELD_NUMBER = 13;
  private dk.via.mithus.protobuf.Cost cost_;
  /**
   * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
   * @return Whether the cost field is set.
   */
  @java.lang.Override
  public boolean hasCost() {
    return cost_ != null;
  }
  /**
   * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
   * @return The cost.
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.Cost getCost() {
    return cost_ == null ? dk.via.mithus.protobuf.Cost.getDefaultInstance() : cost_;
  }
  /**
   * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.CostOrBuilder getCostOrBuilder() {
    return getCost();
  }

  public static final int AMENITY_FIELD_NUMBER = 14;
  private java.util.List<dk.via.mithus.protobuf.Amenity> amenity_;
  /**
   * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
   */
  @java.lang.Override
  public java.util.List<dk.via.mithus.protobuf.Amenity> getAmenityList() {
    return amenity_;
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
   */
  @java.lang.Override
  public java.util.List<? extends dk.via.mithus.protobuf.AmenityOrBuilder> 
      getAmenityOrBuilderList() {
    return amenity_;
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
   */
  @java.lang.Override
  public int getAmenityCount() {
    return amenity_.size();
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.Amenity getAmenity(int index) {
    return amenity_.get(index);
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.AmenityOrBuilder getAmenityOrBuilder(
      int index) {
    return amenity_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
    }
    if (java.lang.Double.doubleToRawLongBits(area_) != 0) {
      output.writeDouble(4, area_);
    }
    if (maxTenants_ != 0) {
      output.writeInt32(5, maxTenants_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(creationDate_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, creationDate_);
    }
    if (housingTypeId_ != 0L) {
      output.writeInt64(7, housingTypeId_);
    }
    if (energyRatingId_ != 0L) {
      output.writeInt64(8, energyRatingId_);
    }
    if (statusId_ != 0L) {
      output.writeInt64(9, statusId_);
    }
    if (landlordId_ != 0L) {
      output.writeInt64(10, landlordId_);
    }
    for (int i = 0; i < image_.size(); i++) {
      output.writeMessage(11, image_.get(i));
    }
    if (address_ != null) {
      output.writeMessage(12, getAddress());
    }
    if (cost_ != null) {
      output.writeMessage(13, getCost());
    }
    for (int i = 0; i < amenity_.size(); i++) {
      output.writeMessage(14, amenity_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
    }
    if (java.lang.Double.doubleToRawLongBits(area_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, area_);
    }
    if (maxTenants_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, maxTenants_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(creationDate_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, creationDate_);
    }
    if (housingTypeId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, housingTypeId_);
    }
    if (energyRatingId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, energyRatingId_);
    }
    if (statusId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, statusId_);
    }
    if (landlordId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, landlordId_);
    }
    for (int i = 0; i < image_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, image_.get(i));
    }
    if (address_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, getAddress());
    }
    if (cost_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, getCost());
    }
    for (int i = 0; i < amenity_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, amenity_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dk.via.mithus.protobuf.PostCreation)) {
      return super.equals(obj);
    }
    dk.via.mithus.protobuf.PostCreation other = (dk.via.mithus.protobuf.PostCreation) obj;

    if (getId()
        != other.getId()) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (java.lang.Double.doubleToLongBits(getArea())
        != java.lang.Double.doubleToLongBits(
            other.getArea())) return false;
    if (getMaxTenants()
        != other.getMaxTenants()) return false;
    if (!getCreationDate()
        .equals(other.getCreationDate())) return false;
    if (getHousingTypeId()
        != other.getHousingTypeId()) return false;
    if (getEnergyRatingId()
        != other.getEnergyRatingId()) return false;
    if (getStatusId()
        != other.getStatusId()) return false;
    if (getLandlordId()
        != other.getLandlordId()) return false;
    if (!getImageList()
        .equals(other.getImageList())) return false;
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (hasCost() != other.hasCost()) return false;
    if (hasCost()) {
      if (!getCost()
          .equals(other.getCost())) return false;
    }
    if (!getAmenityList()
        .equals(other.getAmenityList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + AREA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getArea()));
    hash = (37 * hash) + MAXTENANTS_FIELD_NUMBER;
    hash = (53 * hash) + getMaxTenants();
    hash = (37 * hash) + CREATIONDATE_FIELD_NUMBER;
    hash = (53 * hash) + getCreationDate().hashCode();
    hash = (37 * hash) + HOUSINGTYPEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHousingTypeId());
    hash = (37 * hash) + ENERGYRATINGID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEnergyRatingId());
    hash = (37 * hash) + STATUSID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStatusId());
    hash = (37 * hash) + LANDLORDID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLandlordId());
    if (getImageCount() > 0) {
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImageList().hashCode();
    }
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    if (hasCost()) {
      hash = (37 * hash) + COST_FIELD_NUMBER;
      hash = (53 * hash) + getCost().hashCode();
    }
    if (getAmenityCount() > 0) {
      hash = (37 * hash) + AMENITY_FIELD_NUMBER;
      hash = (53 * hash) + getAmenityList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dk.via.mithus.protobuf.PostCreation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.mithus.protobuf.PostCreation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.PostCreation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.mithus.protobuf.PostCreation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.PostCreation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.mithus.protobuf.PostCreation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.PostCreation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.mithus.protobuf.PostCreation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.PostCreation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dk.via.mithus.protobuf.PostCreation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.PostCreation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.mithus.protobuf.PostCreation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dk.via.mithus.protobuf.PostCreation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dk.via.mithus.protobuf.PostCreation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dk.via.mithus.protobuf.PostCreation)
      dk.via.mithus.protobuf.PostCreationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_PostCreation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_PostCreation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.via.mithus.protobuf.PostCreation.class, dk.via.mithus.protobuf.PostCreation.Builder.class);
    }

    // Construct using dk.via.mithus.protobuf.PostCreation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getImageFieldBuilder();
        getAmenityFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      title_ = "";

      description_ = "";

      area_ = 0D;

      maxTenants_ = 0;

      creationDate_ = "";

      housingTypeId_ = 0L;

      energyRatingId_ = 0L;

      statusId_ = 0L;

      landlordId_ = 0L;

      if (imageBuilder_ == null) {
        image_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        imageBuilder_.clear();
      }
      if (addressBuilder_ == null) {
        address_ = null;
      } else {
        address_ = null;
        addressBuilder_ = null;
      }
      if (costBuilder_ == null) {
        cost_ = null;
      } else {
        cost_ = null;
        costBuilder_ = null;
      }
      if (amenityBuilder_ == null) {
        amenity_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        amenityBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_PostCreation_descriptor;
    }

    @java.lang.Override
    public dk.via.mithus.protobuf.PostCreation getDefaultInstanceForType() {
      return dk.via.mithus.protobuf.PostCreation.getDefaultInstance();
    }

    @java.lang.Override
    public dk.via.mithus.protobuf.PostCreation build() {
      dk.via.mithus.protobuf.PostCreation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dk.via.mithus.protobuf.PostCreation buildPartial() {
      dk.via.mithus.protobuf.PostCreation result = new dk.via.mithus.protobuf.PostCreation(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.title_ = title_;
      result.description_ = description_;
      result.area_ = area_;
      result.maxTenants_ = maxTenants_;
      result.creationDate_ = creationDate_;
      result.housingTypeId_ = housingTypeId_;
      result.energyRatingId_ = energyRatingId_;
      result.statusId_ = statusId_;
      result.landlordId_ = landlordId_;
      if (imageBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          image_ = java.util.Collections.unmodifiableList(image_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.image_ = image_;
      } else {
        result.image_ = imageBuilder_.build();
      }
      if (addressBuilder_ == null) {
        result.address_ = address_;
      } else {
        result.address_ = addressBuilder_.build();
      }
      if (costBuilder_ == null) {
        result.cost_ = cost_;
      } else {
        result.cost_ = costBuilder_.build();
      }
      if (amenityBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          amenity_ = java.util.Collections.unmodifiableList(amenity_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.amenity_ = amenity_;
      } else {
        result.amenity_ = amenityBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dk.via.mithus.protobuf.PostCreation) {
        return mergeFrom((dk.via.mithus.protobuf.PostCreation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dk.via.mithus.protobuf.PostCreation other) {
      if (other == dk.via.mithus.protobuf.PostCreation.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (other.getArea() != 0D) {
        setArea(other.getArea());
      }
      if (other.getMaxTenants() != 0) {
        setMaxTenants(other.getMaxTenants());
      }
      if (!other.getCreationDate().isEmpty()) {
        creationDate_ = other.creationDate_;
        onChanged();
      }
      if (other.getHousingTypeId() != 0L) {
        setHousingTypeId(other.getHousingTypeId());
      }
      if (other.getEnergyRatingId() != 0L) {
        setEnergyRatingId(other.getEnergyRatingId());
      }
      if (other.getStatusId() != 0L) {
        setStatusId(other.getStatusId());
      }
      if (other.getLandlordId() != 0L) {
        setLandlordId(other.getLandlordId());
      }
      if (imageBuilder_ == null) {
        if (!other.image_.isEmpty()) {
          if (image_.isEmpty()) {
            image_ = other.image_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureImageIsMutable();
            image_.addAll(other.image_);
          }
          onChanged();
        }
      } else {
        if (!other.image_.isEmpty()) {
          if (imageBuilder_.isEmpty()) {
            imageBuilder_.dispose();
            imageBuilder_ = null;
            image_ = other.image_;
            bitField0_ = (bitField0_ & ~0x00000001);
            imageBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getImageFieldBuilder() : null;
          } else {
            imageBuilder_.addAllMessages(other.image_);
          }
        }
      }
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      if (other.hasCost()) {
        mergeCost(other.getCost());
      }
      if (amenityBuilder_ == null) {
        if (!other.amenity_.isEmpty()) {
          if (amenity_.isEmpty()) {
            amenity_ = other.amenity_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAmenityIsMutable();
            amenity_.addAll(other.amenity_);
          }
          onChanged();
        }
      } else {
        if (!other.amenity_.isEmpty()) {
          if (amenityBuilder_.isEmpty()) {
            amenityBuilder_.dispose();
            amenityBuilder_ = null;
            amenity_ = other.amenity_;
            bitField0_ = (bitField0_ & ~0x00000002);
            amenityBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAmenityFieldBuilder() : null;
          } else {
            amenityBuilder_.addAllMessages(other.amenity_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dk.via.mithus.protobuf.PostCreation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dk.via.mithus.protobuf.PostCreation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private double area_ ;
    /**
     * <code>double area = 4;</code>
     * @return The area.
     */
    @java.lang.Override
    public double getArea() {
      return area_;
    }
    /**
     * <code>double area = 4;</code>
     * @param value The area to set.
     * @return This builder for chaining.
     */
    public Builder setArea(double value) {
      
      area_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double area = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearArea() {
      
      area_ = 0D;
      onChanged();
      return this;
    }

    private int maxTenants_ ;
    /**
     * <code>int32 maxTenants = 5;</code>
     * @return The maxTenants.
     */
    @java.lang.Override
    public int getMaxTenants() {
      return maxTenants_;
    }
    /**
     * <code>int32 maxTenants = 5;</code>
     * @param value The maxTenants to set.
     * @return This builder for chaining.
     */
    public Builder setMaxTenants(int value) {
      
      maxTenants_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 maxTenants = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxTenants() {
      
      maxTenants_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object creationDate_ = "";
    /**
     * <code>string creationDate = 6;</code>
     * @return The creationDate.
     */
    public java.lang.String getCreationDate() {
      java.lang.Object ref = creationDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creationDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string creationDate = 6;</code>
     * @return The bytes for creationDate.
     */
    public com.google.protobuf.ByteString
        getCreationDateBytes() {
      java.lang.Object ref = creationDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creationDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string creationDate = 6;</code>
     * @param value The creationDate to set.
     * @return This builder for chaining.
     */
    public Builder setCreationDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      creationDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string creationDate = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreationDate() {
      
      creationDate_ = getDefaultInstance().getCreationDate();
      onChanged();
      return this;
    }
    /**
     * <code>string creationDate = 6;</code>
     * @param value The bytes for creationDate to set.
     * @return This builder for chaining.
     */
    public Builder setCreationDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      creationDate_ = value;
      onChanged();
      return this;
    }

    private long housingTypeId_ ;
    /**
     * <code>int64 housingTypeId = 7;</code>
     * @return The housingTypeId.
     */
    @java.lang.Override
    public long getHousingTypeId() {
      return housingTypeId_;
    }
    /**
     * <code>int64 housingTypeId = 7;</code>
     * @param value The housingTypeId to set.
     * @return This builder for chaining.
     */
    public Builder setHousingTypeId(long value) {
      
      housingTypeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 housingTypeId = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearHousingTypeId() {
      
      housingTypeId_ = 0L;
      onChanged();
      return this;
    }

    private long energyRatingId_ ;
    /**
     * <code>int64 energyRatingId = 8;</code>
     * @return The energyRatingId.
     */
    @java.lang.Override
    public long getEnergyRatingId() {
      return energyRatingId_;
    }
    /**
     * <code>int64 energyRatingId = 8;</code>
     * @param value The energyRatingId to set.
     * @return This builder for chaining.
     */
    public Builder setEnergyRatingId(long value) {
      
      energyRatingId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 energyRatingId = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnergyRatingId() {
      
      energyRatingId_ = 0L;
      onChanged();
      return this;
    }

    private long statusId_ ;
    /**
     * <code>int64 statusId = 9;</code>
     * @return The statusId.
     */
    @java.lang.Override
    public long getStatusId() {
      return statusId_;
    }
    /**
     * <code>int64 statusId = 9;</code>
     * @param value The statusId to set.
     * @return This builder for chaining.
     */
    public Builder setStatusId(long value) {
      
      statusId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 statusId = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatusId() {
      
      statusId_ = 0L;
      onChanged();
      return this;
    }

    private long landlordId_ ;
    /**
     * <code>int64 landlordId = 10;</code>
     * @return The landlordId.
     */
    @java.lang.Override
    public long getLandlordId() {
      return landlordId_;
    }
    /**
     * <code>int64 landlordId = 10;</code>
     * @param value The landlordId to set.
     * @return This builder for chaining.
     */
    public Builder setLandlordId(long value) {
      
      landlordId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 landlordId = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearLandlordId() {
      
      landlordId_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<dk.via.mithus.protobuf.Image> image_ =
      java.util.Collections.emptyList();
    private void ensureImageIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        image_ = new java.util.ArrayList<dk.via.mithus.protobuf.Image>(image_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        dk.via.mithus.protobuf.Image, dk.via.mithus.protobuf.Image.Builder, dk.via.mithus.protobuf.ImageOrBuilder> imageBuilder_;

    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public java.util.List<dk.via.mithus.protobuf.Image> getImageList() {
      if (imageBuilder_ == null) {
        return java.util.Collections.unmodifiableList(image_);
      } else {
        return imageBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public int getImageCount() {
      if (imageBuilder_ == null) {
        return image_.size();
      } else {
        return imageBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public dk.via.mithus.protobuf.Image getImage(int index) {
      if (imageBuilder_ == null) {
        return image_.get(index);
      } else {
        return imageBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public Builder setImage(
        int index, dk.via.mithus.protobuf.Image value) {
      if (imageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImageIsMutable();
        image_.set(index, value);
        onChanged();
      } else {
        imageBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public Builder setImage(
        int index, dk.via.mithus.protobuf.Image.Builder builderForValue) {
      if (imageBuilder_ == null) {
        ensureImageIsMutable();
        image_.set(index, builderForValue.build());
        onChanged();
      } else {
        imageBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public Builder addImage(dk.via.mithus.protobuf.Image value) {
      if (imageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImageIsMutable();
        image_.add(value);
        onChanged();
      } else {
        imageBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public Builder addImage(
        int index, dk.via.mithus.protobuf.Image value) {
      if (imageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImageIsMutable();
        image_.add(index, value);
        onChanged();
      } else {
        imageBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public Builder addImage(
        dk.via.mithus.protobuf.Image.Builder builderForValue) {
      if (imageBuilder_ == null) {
        ensureImageIsMutable();
        image_.add(builderForValue.build());
        onChanged();
      } else {
        imageBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public Builder addImage(
        int index, dk.via.mithus.protobuf.Image.Builder builderForValue) {
      if (imageBuilder_ == null) {
        ensureImageIsMutable();
        image_.add(index, builderForValue.build());
        onChanged();
      } else {
        imageBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public Builder addAllImage(
        java.lang.Iterable<? extends dk.via.mithus.protobuf.Image> values) {
      if (imageBuilder_ == null) {
        ensureImageIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, image_);
        onChanged();
      } else {
        imageBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public Builder clearImage() {
      if (imageBuilder_ == null) {
        image_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        imageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public Builder removeImage(int index) {
      if (imageBuilder_ == null) {
        ensureImageIsMutable();
        image_.remove(index);
        onChanged();
      } else {
        imageBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public dk.via.mithus.protobuf.Image.Builder getImageBuilder(
        int index) {
      return getImageFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public dk.via.mithus.protobuf.ImageOrBuilder getImageOrBuilder(
        int index) {
      if (imageBuilder_ == null) {
        return image_.get(index);  } else {
        return imageBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public java.util.List<? extends dk.via.mithus.protobuf.ImageOrBuilder> 
         getImageOrBuilderList() {
      if (imageBuilder_ != null) {
        return imageBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(image_);
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public dk.via.mithus.protobuf.Image.Builder addImageBuilder() {
      return getImageFieldBuilder().addBuilder(
          dk.via.mithus.protobuf.Image.getDefaultInstance());
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public dk.via.mithus.protobuf.Image.Builder addImageBuilder(
        int index) {
      return getImageFieldBuilder().addBuilder(
          index, dk.via.mithus.protobuf.Image.getDefaultInstance());
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public java.util.List<dk.via.mithus.protobuf.Image.Builder> 
         getImageBuilderList() {
      return getImageFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        dk.via.mithus.protobuf.Image, dk.via.mithus.protobuf.Image.Builder, dk.via.mithus.protobuf.ImageOrBuilder> 
        getImageFieldBuilder() {
      if (imageBuilder_ == null) {
        imageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            dk.via.mithus.protobuf.Image, dk.via.mithus.protobuf.Image.Builder, dk.via.mithus.protobuf.ImageOrBuilder>(
                image_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        image_ = null;
      }
      return imageBuilder_;
    }

    private dk.via.mithus.protobuf.Address address_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.mithus.protobuf.Address, dk.via.mithus.protobuf.Address.Builder, dk.via.mithus.protobuf.AddressOrBuilder> addressBuilder_;
    /**
     * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return addressBuilder_ != null || address_ != null;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
     * @return The address.
     */
    public dk.via.mithus.protobuf.Address getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? dk.via.mithus.protobuf.Address.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }
    /**
     * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
     */
    public Builder setAddress(dk.via.mithus.protobuf.Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
        onChanged();
      } else {
        addressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
     */
    public Builder setAddress(
        dk.via.mithus.protobuf.Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
        onChanged();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
     */
    public Builder mergeAddress(dk.via.mithus.protobuf.Address value) {
      if (addressBuilder_ == null) {
        if (address_ != null) {
          address_ =
            dk.via.mithus.protobuf.Address.newBuilder(address_).mergeFrom(value).buildPartial();
        } else {
          address_ = value;
        }
        onChanged();
      } else {
        addressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
     */
    public Builder clearAddress() {
      if (addressBuilder_ == null) {
        address_ = null;
        onChanged();
      } else {
        address_ = null;
        addressBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
     */
    public dk.via.mithus.protobuf.Address.Builder getAddressBuilder() {
      
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
     */
    public dk.via.mithus.protobuf.AddressOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ?
            dk.via.mithus.protobuf.Address.getDefaultInstance() : address_;
      }
    }
    /**
     * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.mithus.protobuf.Address, dk.via.mithus.protobuf.Address.Builder, dk.via.mithus.protobuf.AddressOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dk.via.mithus.protobuf.Address, dk.via.mithus.protobuf.Address.Builder, dk.via.mithus.protobuf.AddressOrBuilder>(
                getAddress(),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    private dk.via.mithus.protobuf.Cost cost_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.mithus.protobuf.Cost, dk.via.mithus.protobuf.Cost.Builder, dk.via.mithus.protobuf.CostOrBuilder> costBuilder_;
    /**
     * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
     * @return Whether the cost field is set.
     */
    public boolean hasCost() {
      return costBuilder_ != null || cost_ != null;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
     * @return The cost.
     */
    public dk.via.mithus.protobuf.Cost getCost() {
      if (costBuilder_ == null) {
        return cost_ == null ? dk.via.mithus.protobuf.Cost.getDefaultInstance() : cost_;
      } else {
        return costBuilder_.getMessage();
      }
    }
    /**
     * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
     */
    public Builder setCost(dk.via.mithus.protobuf.Cost value) {
      if (costBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cost_ = value;
        onChanged();
      } else {
        costBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
     */
    public Builder setCost(
        dk.via.mithus.protobuf.Cost.Builder builderForValue) {
      if (costBuilder_ == null) {
        cost_ = builderForValue.build();
        onChanged();
      } else {
        costBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
     */
    public Builder mergeCost(dk.via.mithus.protobuf.Cost value) {
      if (costBuilder_ == null) {
        if (cost_ != null) {
          cost_ =
            dk.via.mithus.protobuf.Cost.newBuilder(cost_).mergeFrom(value).buildPartial();
        } else {
          cost_ = value;
        }
        onChanged();
      } else {
        costBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
     */
    public Builder clearCost() {
      if (costBuilder_ == null) {
        cost_ = null;
        onChanged();
      } else {
        cost_ = null;
        costBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
     */
    public dk.via.mithus.protobuf.Cost.Builder getCostBuilder() {
      
      onChanged();
      return getCostFieldBuilder().getBuilder();
    }
    /**
     * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
     */
    public dk.via.mithus.protobuf.CostOrBuilder getCostOrBuilder() {
      if (costBuilder_ != null) {
        return costBuilder_.getMessageOrBuilder();
      } else {
        return cost_ == null ?
            dk.via.mithus.protobuf.Cost.getDefaultInstance() : cost_;
      }
    }
    /**
     * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.mithus.protobuf.Cost, dk.via.mithus.protobuf.Cost.Builder, dk.via.mithus.protobuf.CostOrBuilder> 
        getCostFieldBuilder() {
      if (costBuilder_ == null) {
        costBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dk.via.mithus.protobuf.Cost, dk.via.mithus.protobuf.Cost.Builder, dk.via.mithus.protobuf.CostOrBuilder>(
                getCost(),
                getParentForChildren(),
                isClean());
        cost_ = null;
      }
      return costBuilder_;
    }

    private java.util.List<dk.via.mithus.protobuf.Amenity> amenity_ =
      java.util.Collections.emptyList();
    private void ensureAmenityIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        amenity_ = new java.util.ArrayList<dk.via.mithus.protobuf.Amenity>(amenity_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        dk.via.mithus.protobuf.Amenity, dk.via.mithus.protobuf.Amenity.Builder, dk.via.mithus.protobuf.AmenityOrBuilder> amenityBuilder_;

    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public java.util.List<dk.via.mithus.protobuf.Amenity> getAmenityList() {
      if (amenityBuilder_ == null) {
        return java.util.Collections.unmodifiableList(amenity_);
      } else {
        return amenityBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public int getAmenityCount() {
      if (amenityBuilder_ == null) {
        return amenity_.size();
      } else {
        return amenityBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public dk.via.mithus.protobuf.Amenity getAmenity(int index) {
      if (amenityBuilder_ == null) {
        return amenity_.get(index);
      } else {
        return amenityBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public Builder setAmenity(
        int index, dk.via.mithus.protobuf.Amenity value) {
      if (amenityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAmenityIsMutable();
        amenity_.set(index, value);
        onChanged();
      } else {
        amenityBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public Builder setAmenity(
        int index, dk.via.mithus.protobuf.Amenity.Builder builderForValue) {
      if (amenityBuilder_ == null) {
        ensureAmenityIsMutable();
        amenity_.set(index, builderForValue.build());
        onChanged();
      } else {
        amenityBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public Builder addAmenity(dk.via.mithus.protobuf.Amenity value) {
      if (amenityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAmenityIsMutable();
        amenity_.add(value);
        onChanged();
      } else {
        amenityBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public Builder addAmenity(
        int index, dk.via.mithus.protobuf.Amenity value) {
      if (amenityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAmenityIsMutable();
        amenity_.add(index, value);
        onChanged();
      } else {
        amenityBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public Builder addAmenity(
        dk.via.mithus.protobuf.Amenity.Builder builderForValue) {
      if (amenityBuilder_ == null) {
        ensureAmenityIsMutable();
        amenity_.add(builderForValue.build());
        onChanged();
      } else {
        amenityBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public Builder addAmenity(
        int index, dk.via.mithus.protobuf.Amenity.Builder builderForValue) {
      if (amenityBuilder_ == null) {
        ensureAmenityIsMutable();
        amenity_.add(index, builderForValue.build());
        onChanged();
      } else {
        amenityBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public Builder addAllAmenity(
        java.lang.Iterable<? extends dk.via.mithus.protobuf.Amenity> values) {
      if (amenityBuilder_ == null) {
        ensureAmenityIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, amenity_);
        onChanged();
      } else {
        amenityBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public Builder clearAmenity() {
      if (amenityBuilder_ == null) {
        amenity_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        amenityBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public Builder removeAmenity(int index) {
      if (amenityBuilder_ == null) {
        ensureAmenityIsMutable();
        amenity_.remove(index);
        onChanged();
      } else {
        amenityBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public dk.via.mithus.protobuf.Amenity.Builder getAmenityBuilder(
        int index) {
      return getAmenityFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public dk.via.mithus.protobuf.AmenityOrBuilder getAmenityOrBuilder(
        int index) {
      if (amenityBuilder_ == null) {
        return amenity_.get(index);  } else {
        return amenityBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public java.util.List<? extends dk.via.mithus.protobuf.AmenityOrBuilder> 
         getAmenityOrBuilderList() {
      if (amenityBuilder_ != null) {
        return amenityBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(amenity_);
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public dk.via.mithus.protobuf.Amenity.Builder addAmenityBuilder() {
      return getAmenityFieldBuilder().addBuilder(
          dk.via.mithus.protobuf.Amenity.getDefaultInstance());
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public dk.via.mithus.protobuf.Amenity.Builder addAmenityBuilder(
        int index) {
      return getAmenityFieldBuilder().addBuilder(
          index, dk.via.mithus.protobuf.Amenity.getDefaultInstance());
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public java.util.List<dk.via.mithus.protobuf.Amenity.Builder> 
         getAmenityBuilderList() {
      return getAmenityFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        dk.via.mithus.protobuf.Amenity, dk.via.mithus.protobuf.Amenity.Builder, dk.via.mithus.protobuf.AmenityOrBuilder> 
        getAmenityFieldBuilder() {
      if (amenityBuilder_ == null) {
        amenityBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            dk.via.mithus.protobuf.Amenity, dk.via.mithus.protobuf.Amenity.Builder, dk.via.mithus.protobuf.AmenityOrBuilder>(
                amenity_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        amenity_ = null;
      }
      return amenityBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dk.via.mithus.protobuf.PostCreation)
  }

  // @@protoc_insertion_point(class_scope:dk.via.mithus.protobuf.PostCreation)
  private static final dk.via.mithus.protobuf.PostCreation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dk.via.mithus.protobuf.PostCreation();
  }

  public static dk.via.mithus.protobuf.PostCreation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PostCreation>
      PARSER = new com.google.protobuf.AbstractParser<PostCreation>() {
    @java.lang.Override
    public PostCreation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PostCreation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PostCreation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PostCreation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dk.via.mithus.protobuf.PostCreation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

